#region copyright
//----------------------------------------------------------------------
// Copyright 2023 MNB Software
// Licensed under the Apache License, Version 2.0
// You may obtain a copy at http://www.apache.org/licenses/LICENSE-2.0
//----------------------------------------------------------------------
#endregion

// <auto-generated />
using System;

using Aegis.Persistence;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aegis.Persistence.Migrations.Application.Secure
{
	[DbContext(typeof(SecureDbContext))]
	[Migration("20230116090848_Initial_SecureDbContext")]
	partial class InitialSecureDbContext
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasDefaultSchema("aegis-sc")
				.HasAnnotation("ProductVersion", "7.0.2")
				.HasAnnotation("Proxies:ChangeTracking", false)
				.HasAnnotation("Proxies:CheckEquality", false)
				.HasAnnotation("Proxies:LazyLoading", true)
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("Aegis.Persistence.Entities.Application.AuditLog", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uuid");

					b.Property<int>("Action")
						.HasColumnType("integer");

					b.Property<string>("EventName")
						.IsRequired()
						.HasColumnType("text");

					b.Property<int>("Module")
						.HasColumnType("integer");

					b.Property<string>("NewValues")
						.HasColumnType("text");

					b.Property<string>("OldValues")
						.HasColumnType("text");

					b.Property<int>("Subject")
						.HasColumnType("integer");

					b.Property<Guid>("SubjectId")
						.HasColumnType("uuid");

					b.Property<bool>("Succeeded")
						.HasColumnType("boolean");

					b.Property<string>("Summary")
						.IsRequired()
						.HasColumnType("text");

					b.Property<DateTime>("Timestamp")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("UserAgent")
						.HasColumnType("text");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid");

					b.Property<string>("UserIp")
						.HasColumnType("text");

					b.Property<string>("UserName")
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("AuditLogs", "aegis-sc");
				});

			modelBuilder.Entity("Aegis.Persistence.Entities.Application.PersonalDataProtectionKey", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uuid");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("text");

					b.Property<DateTime>("CreatedOn")
						.HasColumnType("timestamp with time zone");

					b.Property<DateTime>("ExpiresOn")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("Key")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("KeyHash")
						.IsRequired()
						.HasColumnType("text");

					b.Property<DateTime?>("UpdatedOn")
						.HasColumnType("timestamp with time zone");

					b.HasKey("Id");

					b.ToTable("PersonalDataProtectionKeys", "aegis-sc");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<string>("FriendlyName")
						.HasColumnType("text");

					b.Property<string>("Xml")
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("DataProtectionKeys", "aegis-sc");
				});
#pragma warning restore 612, 618
		}
	}
}
